### ISSUE TITLE
Fix lux calculation for the new LTR329 Lightsensor

### ISSUE THREAD

**Issue by mariopesch** [sensebox/node-sketch-templater#49]
The lux calculation of the LRT329 Sensor is wrong at the moment. 

See https://github.com/sensebox/SenseBoxMCU-Lib/blob/master/SenseBoxMCU.cpp#L505-L588 for an example to calculate the correct lux values and automatic detection of the sensor type.

**Comment by felixerdy** [comment]
Fixed in a7e0c1b244c80c3d3d177bf7a02d184a107637a0
